services:
  mediawiki:
    image: mediawiki:stable-fpm-alpine
    restart: always
    environment:
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=mariadb
      - MEDIAWIKI_DB_NAME=mediawiki
      - MEDIAWIKI_DB_USER=wikiuser
      - MEDIAWIKI_DB_PASSWORD=secretpassword
    volumes:
      - mediawiki_data:/var/www/html
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - mediawiki_data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mediawiki
  mariadb:
    image: linuxserver/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=wikiuser
      - MYSQL_PASSWORD=secretpassword
      - MYSQL_DATABASE=mediawiki
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/config'
  phpmyadmin:
    image: linuxserver/phpmyadmin:latest
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    depends_on:
      - mariadb
volumes:
  mediawiki_data:
  mariadb_data:

